Class('ShareBoard.Widget.Download', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    does : [ 'Symbie.Widget', 'ShareBoard.Widget.PageReport' ],

    
    have : {
        pageId                  : 'download',
        
        autoHeight              : true,
        
        templateSources         : {
            /*tj:../../../content/html/Download.html
<h1 id="download">Download</h1>

<h2 id="joose2">Joose 2</h2>

<p>The latest release in 2.x series is available here: </p>

<p><a href="http://code.google.com/p/joose-js/downloads/list">http://code.google.com/p/joose-js/downloads/list</a></p>

<h2 id="joose3">Joose 3</h2>

<p>The recommended installation procedure for Joose 3 is described here: <a href="http://openjsan.org/go/?l=Joose.Manual.Installation">http://openjsan.org/go/?l=Joose.Manual.Installation</a></p>

<p>Alternatively, the complete list of releases is available for download here: <a href="http://openjsan.org/go?d=Joose">http://openjsan.org/go?d=Joose</a></p>

<h1 id="gitrepository">Git Repository</h1>

<p>To obtain the latest sources, grab a copy of the Joose <a href="http://github.com/Joose/Joose">repository at github</a></p>
tj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '<h1 id="download">Download</h1>\n\n<h2 id="joose2">Joose 2</h2>\n\n<p>The latest release in 2.x series is available here: </p>\n\n<p><a href="http://code.google.com/p/joose-js/downloads/list">http://code.google.com/p/joose-js/downloads/list</a></p>\n\n<h2 id="joose3">Joose 3</h2>\n\n<p>The recommended installation procedure for Joose 3 is described here: <a href="http://openjsan.org/go/?l=Joose.Manual.Installation">http://openjsan.org/go/?l=Joose.Manual.Installation</a></p>\n\n<p>Alternatively, the complete list of releases is available for download here: <a href="http://openjsan.org/go?d=Joose">http://openjsan.org/go?d=Joose</a></p>\n\n<h1 id="gitrepository">Git Repository</h1>\n\n<p>To obtain the latest sources, grab a copy of the Joose <a href="http://github.com/Joose/Joose">repository at github</a></p>\n'
        }
    }
    
})
