Class('ShareBoard.Widget.Footer', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    
    have : {
        templateSources         : {
            /*tj:../../../templates/footer.tj.html
&copy;2009-2010 <a href="mailto:nickolay8@gmail.com">Nickolay Platonov</a>
<span style="float: right">Powered by <a href="http://symbie.org">Symbie</a></span>tj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '&copy;2009-2010 <a href="mailto:nickolay8@gmail.com">Nickolay Platonov</a>\n<span style="float: right">Powered by <a href="http://symbie.org">Symbie</a></span>'
        }
    }
    
})