Class('ShareBoard.Widget.Home', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    does : [ 'Symbie.Widget', 'ShareBoard.Widget.PageReport' ],

    
    have : {
        pageId                  : 'home',
        
        autoHeight              : true,
        
        templateSources         : {
            /*tj:../../../content/html/Home.html
<h1 id="whatisjoose">WHAT IS Joose?</h1>

<p>Joose is a complete modern object system for JavaScript based on concepts from many programming languages such as Ruby, Smalltalk, Perl and, well, JavaScript. 
It provides "keywords" or "syntactic sugar" for class declaration, object construction, inheritance and more. These keywords feel like they become a part of the language and you don't have to care about the implementation details of all these concepts. </p>

<p>With Joose, you can concentrate on the logical structure of your code, focusing on "what" rather than "how". A class definition with Joose reads like a list of very concise English sentences.</p>

<p>Joose provides complete introspection for all Joose-using classes. This means you can ask classes about their attributes, parents, children, methods, etc., all using a well-defined API.</p>

<p>Joose is based in large part on the <a href="http://search.cpan.org/dist/Moose/lib/Moose.pm">Moose</a> system, which in turn borrows a lot of from Perl 6 object system, as well as drawing on the best ideas from CLOS, Smalltalk, and many other languages.</p>

<h1 id="whatjooseisnot">WHAT Joose is not?</h1>

<p>Joose isn't a new language or sources preprocessor. The code written in Joose, executes like regular JavaScript, and can be run in any modern JavaScript engine.</p>

<h1 id="whyjoose">WHY Joose?</h1>

<p>Joose makes JavaScript OO both simpler and more powerful. It encapsulates JavaScript power tools in high-level declarative APIs which are easy to use. 
Best of all, you don't need to be a wizard to use it. Here's the example of Joose class: </p>

<pre><code>Class('Person', {

    methods : {
        eat : function (food) {
            console.log('yummy')

            return 'yummy'
        }
    }
})
</code></pre>

<p>This is a complete and usable class definition! Another example:</p>

<pre><code>Class('Person.Tidy', {
    isa : Person,

    before : {
        eat : function (food) {
            this.washHands()
        }
    },

    after : {
        eat : function (food) {
            this.brushTeeth()
        }
    },

    methods : {

        washHands : function (food) {
            console.log('washing hands')
        },

        brushTeeth : function (food) {
            console.log('brushing teeth')
        },

        eat : function (food) {
            this.SUPER(food)
        }
    }
})
</code></pre>

<p>Joose makes every attempt to provide as much convenience as possible during class construction/definition, but still stay out of your way if you want it to.
In the same time, if you want to digg about in the guts, Joose lets you do that too, by using and extending its powerful introspection API (aka reflection) 
or by providing your own meta class implementation.</p>
tj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '<h1 id="whatisjoose">WHAT IS Joose?</h1>\n\n<p>Joose is a complete modern object system for JavaScript based on concepts from many programming languages such as Ruby, Smalltalk, Perl and, well, JavaScript. \nIt provides "keywords" or "syntactic sugar" for class declaration, object construction, inheritance and more. These keywords feel like they become a part of the language and you don\'t have to care about the implementation details of all these concepts. </p>\n\n<p>With Joose, you can concentrate on the logical structure of your code, focusing on "what" rather than "how". A class definition with Joose reads like a list of very concise English sentences.</p>\n\n<p>Joose provides complete introspection for all Joose-using classes. This means you can ask classes about their attributes, parents, children, methods, etc., all using a well-defined API.</p>\n\n<p>Joose is based in large part on the <a href="http://search.cpan.org/dist/Moose/lib/Moose.pm">Moose</a> system, which in turn borrows a lot of from Perl 6 object system, as well as drawing on the best ideas from CLOS, Smalltalk, and many other languages.</p>\n\n<h1 id="whatjooseisnot">WHAT Joose is not?</h1>\n\n<p>Joose isn\'t a new language or sources preprocessor. The code written in Joose, executes like regular JavaScript, and can be run in any modern JavaScript engine.</p>\n\n<h1 id="whyjoose">WHY Joose?</h1>\n\n<p>Joose makes JavaScript OO both simpler and more powerful. It encapsulates JavaScript power tools in high-level declarative APIs which are easy to use. \nBest of all, you don\'t need to be a wizard to use it. Here\'s the example of Joose class: </p>\n\n<pre><code>Class(\'Person\', {\n\n    methods : {\n        eat : function (food) {\n            console.log(\'yummy\')\n\n            return \'yummy\'\n        }\n    }\n})\n</code></pre>\n\n<p>This is a complete and usable class definition! Another example:</p>\n\n<pre><code>Class(\'Person.Tidy\', {\n    isa : Person,\n\n    before : {\n        eat : function (food) {\n            this.washHands()\n        }\n    },\n\n    after : {\n        eat : function (food) {\n            this.brushTeeth()\n        }\n    },\n\n    methods : {\n\n        washHands : function (food) {\n            console.log(\'washing hands\')\n        },\n\n        brushTeeth : function (food) {\n            console.log(\'brushing teeth\')\n        },\n\n        eat : function (food) {\n            this.SUPER(food)\n        }\n    }\n})\n</code></pre>\n\n<p>Joose makes every attempt to provide as much convenience as possible during class construction/definition, but still stay out of your way if you want it to.\nIn the same time, if you want to digg about in the guts, Joose lets you do that too, by using and extending its powerful introspection API (aka reflection) \nor by providing your own meta class implementation.</p>\n'
        }
    }
    
})