Class('ShareBoard.Widget.NotFound', {
    
    isa             : 'SymbieX.Template.Shotenjin.Container',
    
    does            : 'Symbie.Widget',
    

    have : {
        templateSources         : {
            /*tj
                <div>Sorry, this page is missing</div>
                <div class="jit_nav_button"></div>
            tj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '\n                <div>Sorry, this page is missing</div>\n                <div class="jit_nav_button"></div>\n            '
        },
        
        canvas                  : null,
        
        ignoreMouse             : false
    },
    
    
    before : {
        
        initComponent : function () {
            
            Ext.apply(this, {
                
                cls : 'ShareBoard-Widget-NotFound',
                
                width : 500,
                height : 350,
                
                style : 'position : relative'
            })
        }
        //eof initComponent
    }
    
})