Class('ShareBoard.Widget.Resources', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    does : [ 'Symbie.Widget', 'ShareBoard.Widget.PageReport' ],

    
    have : {
        pageId                  : 'resources',
        
        autoHeight              : true,
        
        templateSources         : {
            /*tj:../../../content/html/Resources.html
<h1 id="resources">RESOURCES</h1>

<h2 id="documentation">Documentation</h2>

<h3 id="joose2">Joose 2</h3>

<p>Manual &amp; Cookbook: <a href="http://code.google.com/p/joose-js/">http://code.google.com/p/joose-js/</a></p>

<h3 id="joose3">Joose 3</h3>

<p>Manual: <a href="http://openjsan.org/go/?l=Joose.Manual">http://openjsan.org/go/?l=Joose.Manual</a></p>

<p>Cookbook: <a href="http://openjsan.org/go/?l=Joose.Cookbook">http://openjsan.org/go/?l=Joose.Cookbook</a></p>

<h2 id="community">Community</h2>

<p>Mailing list: <a href="http://groups.google.com/group/joose-js">http://groups.google.com/group/joose-js</a></p>

<p>Forum: <a href="http://joose.it/forum">http://joose.it/forum</a></p>

<p>IRC: <a href="http://webchat.freenode.net/?randomnick=1&amp;channels=joose&amp;prompt=1">#joose</a> on freenode </p>

<h2 id="blogs">Blogs</h2>

<p>Malte Ubl: <a href="http://www.nonblocking.io/">http://www.nonblocking.io/</a></p>

<h2 id="coreextensions">Core extensions</h2>

<p>Singleton pattern: <a href="http://openjsan.org/go/?l=JooseX.Class.Singleton">http://openjsan.org/go/?l=JooseX.Class.Singleton</a></p>

<p>Additional features for attributes: <a href="http://openjsan.org/go/?l=JooseX.Attribute">http://openjsan.org/go/?l=JooseX.Attribute</a></p>

<p>Dependencies (browser oriented): <a href="http://openjsan.org/go/?l=JooseX.Namespace.Depended">http://openjsan.org/go/?l=JooseX.Namespace.Depended</a></p>
tj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '<h1 id="resources">RESOURCES</h1>\n\n<h2 id="documentation">Documentation</h2>\n\n<h3 id="joose2">Joose 2</h3>\n\n<p>Manual &amp; Cookbook: <a href="http://code.google.com/p/joose-js/">http://code.google.com/p/joose-js/</a></p>\n\n<h3 id="joose3">Joose 3</h3>\n\n<p>Manual: <a href="http://openjsan.org/go/?l=Joose.Manual">http://openjsan.org/go/?l=Joose.Manual</a></p>\n\n<p>Cookbook: <a href="http://openjsan.org/go/?l=Joose.Cookbook">http://openjsan.org/go/?l=Joose.Cookbook</a></p>\n\n<h2 id="community">Community</h2>\n\n<p>Mailing list: <a href="http://groups.google.com/group/joose-js">http://groups.google.com/group/joose-js</a></p>\n\n<p>Forum: <a href="http://joose.it/forum">http://joose.it/forum</a></p>\n\n<p>IRC: <a href="http://webchat.freenode.net/?randomnick=1&amp;channels=joose&amp;prompt=1">#joose</a> on freenode </p>\n\n<h2 id="blogs">Blogs</h2>\n\n<p>Malte Ubl: <a href="http://www.nonblocking.io/">http://www.nonblocking.io/</a></p>\n\n<h2 id="coreextensions">Core extensions</h2>\n\n<p>Singleton pattern: <a href="http://openjsan.org/go/?l=JooseX.Class.Singleton">http://openjsan.org/go/?l=JooseX.Class.Singleton</a></p>\n\n<p>Additional features for attributes: <a href="http://openjsan.org/go/?l=JooseX.Attribute">http://openjsan.org/go/?l=JooseX.Attribute</a></p>\n\n<p>Dependencies (browser oriented): <a href="http://openjsan.org/go/?l=JooseX.Namespace.Depended">http://openjsan.org/go/?l=JooseX.Namespace.Depended</a></p>\n'
        }
    }
    
})